In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2

In [2]:
data1=pd.read_csv ("manipulated data.csv")
data=data1.drop('sl',axis=1)

In [3]:
data.shape

(187, 59)

In [4]:
x=data.drop('survival_status',axis=1)
y=data['survival_status']

In [5]:
bestfeatures=SelectKBest(score_func=chi2,k=5)
fit=bestfeatures.fit(x,y)
dfscores=pd.DataFrame(fit.scores_)
dfcolumns=pd.DataFrame(x.columns)
featureScores=pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns=['Specs','Score']

In [6]:
x_new=pd.DataFrame(bestfeatures.transform(x))

In [7]:
featureScores

                                Specs         Score
0                           donor_age  1.386350e+00
1                       recipient_age  2.181215e+01
2                 recipient_body_mass  1.152398e+02
3                    CD34_x1e6_per_kg  3.306592e+01
4                     CD3_x1e8_per_kg  3.046170e+01
5                   CD3_to_CD34_ratio  2.290980e+01
6                        ANC_recovery  5.996503e+06
7                        PLT_recovery  2.039048e+07
8           time_to_acute_GvHD_III_IV  4.250331e+05
9                       survival_time  8.292401e+04
10             donor_age_below_35_yes  1.078205e+00
11                        donor_ABO_A  7.892019e-01
12                       donor_ABO_AB  2.135556e+00
13                        donor_ABO_B  7.619048e-02
14                  donor_CMV_present  2.630137e-01
15         recipient_age_below_10_yes  1.996296e+00
16            recipient_age_int_10_20  1.941573e+00
17             recipient_age_int_5_10  3.764706e-01
18              recipient_gender_male  4.285714e-02
19                    recipient_ABO_A  3.197368e-01
20                   recipient_ABO_AB  2.564103e-01
21                    recipient_ABO_B  4.266667e-02
22                  recipient_rh_plus  4.602083e-01
23              recipient_CMV_present  1.361111e-01
24                        disease_AML  0.000000e+00
25                    disease_chronic  1.896296e-01
26                   disease_lymphoma  1.080000e+01
27               disease_nonmalignant  8.166667e-01
28         disease_group_nonmalignant  8.166667e-01
29                 gender_match_other  5.376344e-03
30               ABO_match_mismatched  3.380247e-01
31                       CMV_status_1  1.408046e+00
32                       CMV_status_2  3.555556e-02
33                       CMV_status_3  1.984496e-01
34                   HLA_match_10-Jul  4.266667e-01
35                   HLA_match_10-Oct  1.280142e-01
36                   HLA_match_10-Sep  1.312821e-01
37            HLA_mismatch_mismatched  1.071429e-02
38                          antigen_1  4.063492e-01
39                          antigen_2  6.111111e-02
40                          antigen_3  3.857143e-01
41                            allel_1  7.333333e-02
42                            allel_2  3.750000e-02
43                            allel_3  5.000000e-02
44                            allel_4  1.200000e+00
45                HLA_group_1_matched  1.280142e-01
46             HLA_group_1_mismatched  4.266667e-01
47              HLA_group_1_one_allel  3.809524e-02
48            HLA_group_1_one_antigen  7.936508e-02
49            HLA_group_1_three_diffs  6.750000e-01
50              HLA_group_1_two_diffs  2.807018e-02
51                     risk_group_low  1.505367e+00
52  stem_cell_source_peripheral_blood  6.703448e-01
53                tx_post_relapse_yes  2.204348e+00
54           acute_GvHD_II_III_IV_yes  3.440476e-01
55              acute_GvHD_III_IV_yes  2.340833e+00
56         extensive_chronic_GvHD_yes  4.543011e+00
57                        relapse_yes  1.520119e+01

In [8]:
x_new.describe()

                0               1               2               3            4
count  187.000000      187.000000      187.000000      187.000000   187.000000
mean    35.884492    26752.866310    90937.919786   775408.042781   938.743316
std     19.752157   161747.200525   288242.407688   418425.252689   849.589495
min      6.000000        9.000000        9.000000       10.000000     6.000000
25%     19.000000       13.000000       16.000000  1000000.000000   168.500000
50%     33.000000       15.000000       21.000000  1000000.000000   676.000000
75%     50.700000       17.000000       37.000000  1000000.000000  1604.000000
max    103.400000  1000000.000000  1000000.000000  1000000.000000  3364.000000

In [9]:
featureScores.sort_values(['Score'],ascending=False)

                                Specs         Score
7                        PLT_recovery  2.039048e+07
6                        ANC_recovery  5.996503e+06
8           time_to_acute_GvHD_III_IV  4.250331e+05
9                       survival_time  8.292401e+04
2                 recipient_body_mass  1.152398e+02
3                    CD34_x1e6_per_kg  3.306592e+01
4                     CD3_x1e8_per_kg  3.046170e+01
5                   CD3_to_CD34_ratio  2.290980e+01
1                       recipient_age  2.181215e+01
57                        relapse_yes  1.520119e+01
26                   disease_lymphoma  1.080000e+01
56         extensive_chronic_GvHD_yes  4.543011e+00
55              acute_GvHD_III_IV_yes  2.340833e+00
53                tx_post_relapse_yes  2.204348e+00
12                       donor_ABO_AB  2.135556e+00
15         recipient_age_below_10_yes  1.996296e+00
16            recipient_age_int_10_20  1.941573e+00
51                     risk_group_low  1.505367e+00
31                       CMV_status_1  1.408046e+00
0                           donor_age  1.386350e+00
44                            allel_4  1.200000e+00
10             donor_age_below_35_yes  1.078205e+00
28         disease_group_nonmalignant  8.166667e-01
27               disease_nonmalignant  8.166667e-01
11                        donor_ABO_A  7.892019e-01
49            HLA_group_1_three_diffs  6.750000e-01
52  stem_cell_source_peripheral_blood  6.703448e-01
22                  recipient_rh_plus  4.602083e-01
34                   HLA_match_10-Jul  4.266667e-01
46             HLA_group_1_mismatched  4.266667e-01
38                          antigen_1  4.063492e-01
40                          antigen_3  3.857143e-01
17             recipient_age_int_5_10  3.764706e-01
54           acute_GvHD_II_III_IV_yes  3.440476e-01
30               ABO_match_mismatched  3.380247e-01
19                    recipient_ABO_A  3.197368e-01
14                  donor_CMV_present  2.630137e-01
20                   recipient_ABO_AB  2.564103e-01
33                       CMV_status_3  1.984496e-01
25                    disease_chronic  1.896296e-01
23              recipient_CMV_present  1.361111e-01
36                   HLA_match_10-Sep  1.312821e-01
35                   HLA_match_10-Oct  1.280142e-01
45                HLA_group_1_matched  1.280142e-01
48            HLA_group_1_one_antigen  7.936508e-02
13                        donor_ABO_B  7.619048e-02
41                            allel_1  7.333333e-02
39                          antigen_2  6.111111e-02
43                            allel_3  5.000000e-02
18              recipient_gender_male  4.285714e-02
21                    recipient_ABO_B  4.266667e-02
47              HLA_group_1_one_allel  3.809524e-02
42                            allel_2  3.750000e-02
32                       CMV_status_2  3.555556e-02
50              HLA_group_1_two_diffs  2.807018e-02
37            HLA_mismatch_mismatched  1.071429e-02
29                 gender_match_other  5.376344e-03
24                        disease_AML  0.000000e+00

In [10]:
featureScores.sort_values(['Score'],ascending=False).to_csv('chi squared results sorted.csv')

In [11]:
feature_selected_data=pd.concat([x_new,y],axis=1)

In [12]:
feature_selected_data.to_csv('5_feature_selected_data.csv')